### PR TITLE
Fix library location for g_error_free

### LINKED ISSUE #38: Error with g_error_free
Just ran into the following error on `master` on Windows:
```
  Got exception outside of a @test
  ccall: could not find function g_error_free in library C:\Users\david\.julia\packages\Rsvg\0R8IA\deps\usr\bin\librsvg-2-2.dll
  Stacktrace:
   [1] handle_new_from_data(::String) at C:\Users\david\.julia\packages\Rsvg\0R8IA\src\calls.jl:111
```
@giordano, any idea?

I think that means we should probably hold off from tagging a release...

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #38. @giordano, this should fix it, right?

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -84,3 +84,9 @@ d = test_get_dimension(f);
 @test d.width == 576
 
 end
+
+@testset "error handling" begin
+
+@test_throws ErrorException Rsvg.handle_new_from_data("not a valid data input")
```
Comment (giordano) [inline test/runtests.jl:90]: Can this test be more specific?  `ErrorException` is what is thrown when a function is not found in a library, so that this tests would pass also without the fix

**Review by giordano — APPROVED** [review]
Ok, the test now seems more effective (I tried in my fork to remove the fix and run the same test as this PR and they fail only on Windows).

We've also got confirmation from Jameson on slack that calling the function directly in the library where it's actually defined is the right thing to do.

**Comment by davidanthoff** [comment]
Alright, I think ready to be merged :)
